"use client";

import { ChangeEvent, DragEvent, useMemo, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

type Provider = "openai" | "gemini";
type Stage = "input" | "process" | "output";
type SummaryStyle = "executive" | "action" | "concise";
type SummaryLength = "short" | "standard" | "detailed";
const PROVIDERS = { openai: { label: "OpenAI", model: "gpt-5-mini", placeholder: "sk-proj-..." }, gemini: { label: "Gemini", model: "gemini-3.5-flash-lite", placeholder: "AIza..." } } as const;
const MODEL_OPTIONS: Record<Provider, string[]> = { openai: ["gpt-5-mini", "gpt-5", "gpt-4.1-mini"], gemini: ["gemini-3.5-flash-lite", "gemini-3.5-flash"] };
const STYLES: Record<SummaryStyle, { label: string; description: string }> = { executive: { label: "임원 브리핑", description: "결론과 리스크 중심" }, action: { label: "실행 중심", description: "담당자·기한·액션 중심" }, concise: { label: "간결 요약", description: "핵심만 빠르게" } };
const LENGTHS: Record<SummaryLength, { label: string; description: string }> = { short: { label: "짧게", description: "핵심 5~8줄" }, standard: { label: "표준", description: "업무 공유용" }, detailed: { label: "상세하게", description: "맥락까지 포함" } };
const SUMMARY_PROMPT = `당신은 실무 회의록을 정리하는 전문 비서입니다. 아래 회의록만 근거로 한국어 마크다운 보고서를 작성하세요.
반드시 다음 순서를 따르세요.
# 회의 요약
## 한눈에 보기
- 회의 목적과 결론을 요약
## 핵심 논의
- 주제별 핵심 내용과 맥락
## 결정 사항
- 확정된 사항만 불릿으로 정리. 없으면 "확정된 결정 없음"
## 액션 아이템
| 담당자 | 할 일 | 기한 |
| --- | --- | --- |
담당자나 기한이 불명확하면 "미정"으로 표시
## 미결 이슈
- 추가 논의나 확인이 필요한 내용
사실을 추측하지 말고 중복 표현을 제거하세요.`;

function SparkIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2.8c.7 4.2 2.8 6.3 7 7-4.2.7-6.3 2.8-7 7-.7-4.2-2.8-7-7-7 4.2-.7 6.3-2.8 7-7Z" /><path d="M19 16.5c.25 1.5 1 2.25 2.5 2.5-1.5.25-2.25 1-2.5 2.5-.25-1.5-1-2.25-2.5-2.5 1.5-.25 2.25-2.5Z" /></svg>; }
function FileIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 2.75h6.2L18.25 7.8V21.25H7V2.75Z" /><path d="M13 3v5h5M9.5 12h6M9.5 15h6M9.5 18h4" /></svg>; }
function UploadIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 16V4m0 0L7.5 8.5M12 4l4.5 4.5M5 15.5v3.75h14V15.5" /></svg>; }

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [stage, setStage] = useState<Stage>("input");
  const [provider, setProvider] = useState<Provider>("openai"); const [model, setModel] = useState(PROVIDERS.openai.model);
  const [apiKey, setApiKey] = useState(""); const [file, setFile] = useState<File | null>(null); const [transcript, setTranscript] = useState("");
  const [summaryStyle, setSummaryStyle] = useState<SummaryStyle>("action"); const [summaryLength, setSummaryLength] = useState<SummaryLength>("standard");
  const [dragging, setDragging] = useState(false); const [loading, setLoading] = useState(false); const [result, setResult] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [copied, setCopied] = useState(false);
  const providerMeta = PROVIDERS[provider]; const fileSize = useMemo(() => file ? (file.size < 1024 * 1024 ? `${Math.ceil(file.size / 1024)} KB` : `${(file.size / 1024 / 1024).toFixed(1)} MB`) : "", [file]);
  function validateFile(nextFile?: File) { if (!nextFile) return; if (!nextFile.name.toLowerCase().endsWith(".docx")) { setError(".docx 형식의 회의록만 업로드할 수 있습니다."); return; } if (nextFile.size > 20 * 1024 * 1024) { setError("파일 크기는 20MB 이하여야 합니다."); return; } setFile(nextFile); setError(""); }
  function handleFileChange(event: ChangeEvent<HTMLInputElement>) { validateFile(event.target.files?.[0]); event.target.value = ""; }
  function handleDrop(event: DragEvent<HTMLDivElement>) { event.preventDefault(); setDragging(false); validateFile(event.dataTransfer.files?.[0]); }
  function selectProvider(next: Provider) { setProvider(next); setModel(PROVIDERS[next].model); setApiKey(""); setError(""); setNotice(""); }
  async function prepareProcess() { setError(""); if (!file && !transcript.trim()) { setError("파일을 업로드하거나 회의록 전문을 붙여넣어 주세요."); return; } if (!apiKey.trim()) { setError(`${providerMeta.label} API 키를 입력해 주세요.`); return; } if (file) { try { const mammoth = await import("mammoth/mammoth.browser"); const extracted = await mammoth.extractRawText({ arrayBuffer: await file.arrayBuffer() }); if (!extracted.value.trim()) throw new Error("문서에서 텍스트를 찾지 못했습니다."); setTranscript(extracted.value.trim()); } catch (e) { setError(e instanceof Error ? e.message : "문서를 읽지 못했습니다."); return; } } setStage("process"); }
  async function callOpenAI(text: string, selectedModel: string, prompt: string) { const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { Authorization: `Bearer ${apiKey.trim()}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: selectedModel, instructions: prompt, input: `다음 회의록을 요약하세요.\n\n--- 회의록 시작 ---\n${text}\n--- 회의록 끝 ---` }) }); const data = await response.json(); if (!response.ok) throw new Error(data?.error?.message || "OpenAI 요청에 실패했습니다."); const output = data.output_text || data.output?.flatMap((item: { content?: Array<{ text?: string }> }) => item.content || []).map((item: { text?: string }) => item.text || "").join("\n"); if (!output) throw new Error("요약 결과를 받지 못했습니다."); return output; }
  async function requestGemini(text: string, model: string, prompt: string) { const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(apiKey.trim())}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ systemInstruction: { parts: [{ text: prompt }] }, contents: [{ role: "user", parts: [{ text: `다음 회의록을 요약하세요.\n\n--- 회의록 시작 ---\n${text}\n--- 회의록 끝 ---` }] }], generationConfig: { temperature: 0.2 } }) }); const data = await response.json(); if (!response.ok) { const e = new Error(data?.error?.message || "Gemini 요청에 실패했습니다.") as Error & { status?: number }; e.status = response.status; throw e; } const output = data.candidates?.[0]?.content?.parts?.map((part: { text?: string }) => part.text || "").join("\n"); if (!output) throw new Error("요약 결과를 받지 못했습니다."); return output; }
  async function callGemini(text: string, selectedModel: string, prompt: string) { try { return await requestGemini(text, selectedModel, prompt); } catch (e) { if ((e as Error & { status?: number }).status === 404 && selectedModel === "gemini-3.5-flash-lite") { setNotice("Flash-Lite 모델을 사용할 수 없어 Gemini Flash로 자동 전환했습니다."); return requestGemini(text, "gemini-3.5-flash", prompt); } throw e; } }
  async function summarize() { setLoading(true); setError(""); setNotice(""); const prompt = `${SUMMARY_PROMPT}\n\n요약 스타일: ${STYLES[summaryStyle].label} (${STYLES[summaryStyle].description})\n출력 분량: ${LENGTHS[summaryLength].label} (${LENGTHS[summaryLength].description})`; try { const summary = provider === "openai" ? await callOpenAI(transcript, model, prompt) : await callGemini(transcript, model, prompt); setResult(summary); setStage("output"); } catch (e) { const message = e instanceof Error ? e.message : "요약 중 문제가 발생했습니다."; setError(message.includes("Failed to fetch") ? "API에 연결하지 못했습니다. 네트워크 또는 브라우저 보안 설정을 확인해 주세요." : message); } finally { setLoading(false); } }
  async function copyResult() { await navigator.clipboard.writeText(result); setCopied(true); window.setTimeout(() => setCopied(false), 1600); }
  function downloadResult() { const blob = new Blob([result], { type: "text/markdown;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${file?.name.replace(/\.docx$/i, "") || "회의록"}-요약.md`; link.click(); URL.revokeObjectURL(url); }
  const stageIndex = stage === "input" ? 1 : stage === "process" ? 2 : 3;
  return <main><header className="topbar"><a className="brand" href="#top" aria-label="회의록 요약기 홈"><span className="brand-mark"><SparkIcon /></span><span>Minutes.</span></a><div className="privacy-chip"><span className="privacy-dot" /> API 키는 저장되지 않습니다</div></header><section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">AI MEETING ASSISTANT / 3-STEP WORKFLOW</p><h1>회의록을<br />입력하고,<br />실행하세요.</h1><p className="hero-description">복잡한 설정은 단계별로 나누고,<br className="desktop-break" />결정 사항과 액션 아이템은 한 번에 정리합니다.</p><div className="feature-row"><span><b>01</b> INPUT</span><span><b>02</b> PROCESS</span><span><b>03</b> OUTPUT</span></div></div>
  <div className="workspace-card"><div className="progress"><div className={`progress-line step-${stageIndex}`} /><div className="progress-step active"><span>01</span><b>Input</b></div><div className={`progress-step ${stageIndex >= 2 ? "active" : ""}`}><span>02</span><b>Process</b></div><div className={`progress-step ${stageIndex >= 3 ? "active" : ""}`}><span>03</span><b>Output</b></div></div>
  {stage === "input" && <div className="stage-panel"><div className="stage-title"><div><p className="stage-kicker">STEP 01 / INPUT</p><h2>회의록을 준비하세요.</h2><p>파일 또는 회의록 전문을 입력하고<br />사용할 AI 설정을 선택합니다.</p></div><span className="stage-icon"><UploadIcon /></span></div>{file ? <div className="file-card"><span className="file-icon"><FileIcon /></span><span className="file-meta"><strong>{file.name}</strong><small>{fileSize} · DOCX</small></span><button className="remove-file" type="button" aria-label="파일 제거" onClick={() => setFile(null)}>×</button></div> : <div className={`dropzone ${dragging ? "is-dragging" : ""}`} onDragOver={(e) => { e.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={handleDrop} onClick={() => inputRef.current?.click()} role="button" tabIndex={0} onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") inputRef.current?.click(); }}><span className="upload-icon"><UploadIcon /></span><strong>파일을 끌어놓거나 클릭하세요</strong><small>.docx · 최대 20MB</small></div>}<input ref={inputRef} className="sr-only" type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={handleFileChange} /><div className="or-divider"><span>또는</span></div><label className="transcript-label"><span>회의록 전문 붙여넣기</span><textarea value={transcript} onChange={(e) => setTranscript(e.target.value)} placeholder="회의록 텍스트를 직접 붙여넣을 수 있습니다." rows={4} /></label><div className="divider" /><div className="step-heading compact"><span className="step-number">A</span><div><h2>AI 엔진 및 API 키</h2><p>키는 브라우저에서 요청할 때만 사용됩니다.</p></div></div><div className="provider-toggle" role="tablist" aria-label="요약 엔진 선택"><button className={provider === "openai" ? "active" : ""} type="button" onClick={() => selectProvider("openai")}><span className="openai-glyph">✦</span> OpenAI</button><button className={provider === "gemini" ? "active" : ""} type="button" onClick={() => selectProvider("gemini")}><span className="gemini-glyph">◆</span> Gemini</button></div><div className="field-grid"><label><span>모델 기본값</span><div className="model-field"><span>{providerMeta.model}</span><small>기본값</small></div></label><label><span>API 키</span><input type="password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} placeholder={providerMeta.placeholder} autoComplete="off" spellCheck={false} /></label></div>{error && <p className="message error-message" role="alert">{error}</p>}<button className="primary-button" type="button" onClick={prepareProcess}>Process 설정으로 <span>→</span></button><p className="security-note">키와 문서 내용은 선택한 AI API 요청에만 사용됩니다.</p></div>}
  {stage === "process" && <div className="stage-panel"><div className="stage-title"><div><p className="stage-kicker">STEP 02 / PROCESS</p><h2>어떻게 정리할까요?</h2><p>보고서의 관점과 분량을 선택하면<br />목적에 맞는 결과를 생성합니다.</p></div><span className="stage-icon"><SparkIcon /></span></div><div className="setting-group"><div className="setting-label"><b>요약 스타일</b><span>무엇을 강조할까요?</span></div><div className="choice-grid">{(Object.keys(STYLES) as SummaryStyle[]).map((key) => <button key={key} className={`choice-card ${summaryStyle === key ? "selected" : ""}`} type="button" onClick={() => setSummaryStyle(key)}><strong>{STYLES[key].label}</strong><small>{STYLES[key].description}</small></button>)}</div></div><div className="setting-group"><div className="setting-label"><b>출력 분량</b><span>얼마나 자세하게?</span></div><div className="choice-grid length-grid">{(Object.keys(LENGTHS) as SummaryLength[]).map((key) => <button key={key} className={`choice-card ${summaryLength === key ? "selected" : ""}`} type="button" onClick={() => setSummaryLength(key)}><strong>{LENGTHS[key].label}</strong><small>{LENGTHS[key].description}</small></button>)}</div></div>{error && <p className="message error-message" role="alert">{error}</p>}{notice && <p className="message notice-message">{notice}</p>}<div className="button-row"><button className="secondary-button" type="button" onClick={() => setStage("input")}>← 이전</button><button className="primary-button" type="button" onClick={summarize} disabled={loading}>{loading ? <><span className="spinner" /> 요약 중</> : <>보고서 만들기 <span>→</span></>}</button></div></div>}
  {stage === "output" && <div className="stage-panel output-panel"><div className="stage-title"><div><p className="stage-kicker">STEP 03 / OUTPUT</p><h2>보고서가 완성됐습니다.</h2><p>내용을 확인하고 바로 공유하거나<br />마크다운 파일로 저장하세요.</p></div><span className="stage-icon success">✓</span></div>{notice && <p className="message notice-message">{notice}</p>}<article className="markdown-body"><ReactMarkdown remarkPlugins={[remarkGfm]}>{result}</ReactMarkdown></article><div className="output-actions"><button type="button" onClick={copyResult}>{copied ? "복사됨" : "복사"}</button><button type="button" onClick={downloadResult}>.md 저장</button></div><button className="secondary-button full-button" type="button" onClick={() => setStage("process")}>← 설정으로 돌아가기</button></div>}</div></section><footer><span>Minutes.</span><p>당신의 회의를 실행 가능한 기록으로.</p></footer></main>;
}
